### ISSUE TITLE
Problem with Timepicker in a modal

### ISSUE THREAD

**Issue by Moxide** [mydea/ember-date-components#5] opened 2016-12-01 10:30 UTC
Hello,
I'm trying to use ember-date-components in a Bootstrap's modal.

The date picker is working great, but I face an issue with the time picker:
When the I click on the time input, the time list is showing, including a scrollbar.
When I click on the scrollbar, the list closes immediately, I don't have time to scroll up or down.

In fact, when I click the scrollbar, the input looses focus , so the ```focus-out``` action is triggered and the list closes.
Temporarily, I disabled the ```focus-out``` action, but the list is closing only if the user picks a time, not if he clicks out of the list.

Can you give me some insights on how to solve this issue ?
Thanks !

**Comment by mydea** [comment] 2016-12-01 10:53
Hmm, I just checked, and it works fine in Chrome, FF and Edge. I could reproduce the problem in IE 11, though.

Since IE 11 is being phased out anyhow, and you can still kind-of use it by simply using the scroll wheel, I'm a bit hesitant about changing this. I would, however, gladly accept a PR that fixes this problem, although to be honest I don't really know how this should look/work like.

**Comment by Moxide** [comment] 2016-12-01 11:15
Thanks for your quick answer !
Actually, the problem appears only in a modal (with FF and Chrome), it's working fine out of a modal ;-)
I'm trying to see how other components (such as ember-power-select) are handling the close action...

**Comment by mydea** [comment] 2017-04-12 12:18
Could you check if this is fixed in the 1.0.0-beta.0 release? I migrated to use ember-basic-dropdown (which is also what ember-power-select) uses, so that might hopefully be fixed now.

**Comment by Moxide** [comment] 2017-04-15 16:17
Hello,
I just tested, the problem remained... I removed the `focus-out` event and it's working in a modal.
I had to pass the ember-drop-down's  `renderInPlace` option in date and time pickers to make them appear in the modal (without this option, the dropdowns don't show up).
You can see these modifications and a few others in [my fork.](https://github.com/Moxide/ember-date-components).
Thanks.

**Comment by mydea** [comment] 2017-04-18 06:25
Hmm.. so I might add a `renderInPlace` option to the date picker to accommodate this option.

**Comment by Moxide** [comment] 2017-04-18 10:43
Yes, for both time and date pickers, it would be great ;-)

**Closed** 2017-07-06 06:29 UTC
